FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y make python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

COPY . /workspace

RUN cd /workspace && make install-test
RUN cd /workspace && make test
RUN cd /workspace && make lint
RUN cd /workspace && make docs