FROM quay.io/natlibfi/annif:0.59.0

# ARG UID=1000
# ARG GID=1000

USER root

# add unprivilged user
# RUN groupadd -g $GID slub && useradd --uid $UID --gid $GID -s /bin/bash slub
# USER slub

ENTRYPOINT ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:5000", "--timeout", "600"]
